name: Build and Push
on:
  push:
    #branches:
    #- release/v[0-9]+.[0-9]+ 

jobs:
  Scanning-Security-Vulnerabilities:
    if: "!startsWith(github.event.head_commit.message, '#NORUN')"
    runs-on: ubuntu-latest
    steps:             
      - name: Checkout source code
        uses: actions/checkout@v4.1.4
        with:
          ref: ${{ github.base_ref }}

      - name: Run Aqua Security Trivy for HIGH severity
        id: trivy
        uses: aquasecurity/trivy-action@master
        with:          
          scan-type: 'fs'
          format: 'table'
          severity: 'HIGH'
          output: 'trivy-scan.txt'

      - name: Echo contents of trivy-scan.txt
        run: |
            if test -f trivy-scan.txt; then
                cat trivy-scan.txt
            else
                echo "trivy-scan.txt does not exist."
                exit 1
            fi



      # - name: Slack Notification on failure
      #   uses: rtCamp/action-slack-notify@v2
      #   env:
      #     #SLACK_CHANNEL: 
      #     SLACK_COLOR: failure
      #     SLACK_TITLE: '*Scan failed - Jefri*'
      #     SLACK_MESSAGE: 'Failed trivy scan, see uploaded report'
      #     #SLACK_FILE_UPLOAD: trivy-scan.txt
      #     SLACK_WEBHOOK: ${{ secrets.RICH_WEBHOOK }}
      #     #SLACK_WEBHOOK: ${{ secrets.SLACK_TEST_SUBMISSION }}
      #     #SLACK_TOKEN: ${{ secrets.RICH_TOKEN }}

      # - name: Slack upload of vulnerability report
      #   uses: MeilCli/slack-upload-file@v4      
      #   with:
      #     slack_token: ${{ secrets.RICH_TOKEN }}
      #     #slack_token: ${{ secrets.SLACK_FILE_UPLOAD }}
      #     channel_id: ${{ secrets.RICH_CHANNELID }}
      #     #channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
      #     file_path: 'trivy-scan.txt'
      #     initial_comment: 'Scan report by Too Chang Geng Jefri'

      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        id: build-push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: joot24/go-fortune:${{ github.sha }}     

      - name: Get Docker Hub image URL
        id: get-image-url
        run: |
            IMAGE_NAME=$(echo ${{ steps.build-push.outputs.digest }} | cut -d':' -f1)
            IMAGE_URL="docker.io/${{ env.DOCKERHUB_USERNAME }}/$IMAGE_NAME"
            echo "IMAGE_URL=$IMAGE_URL" >> $GITHUB_ENV

      - name: Slack Notification on success
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: success
          SLACK_TITLE: '*Image build and signed*'
          SLACK_MESSAGE: |            
            *Name:* Too Chang Geng Jefri
            *Matriculation:* A0035383H
            *Email:* e1332826@u.nus.edu
            *Git:* https://github.com/${{ github.repository }}    
            *Image:* ${{ env.IMAGE_URL }}
          SLACK_WEBHOOK: ${{ secrets.RICH_WEBHOOK }}
          #SLACK_WEBHOOK: ${{ secrets.SLACK_TEST_SUBMISSION }}