name: Build and Push
on:
  push:
    #branches:
    #- release/v[0-9]+.[0-9]+ 

jobs:
  Scanning-Security-Vulnerabilities:
    if: "!startsWith(github.event.head_commit.message, '#NORUN')"
    runs-on: ubuntu-latest
    steps:             
      - name: Checkout source code
        uses: actions/checkout@v4.1.4
        with:
          ref: ${{ github.base_ref }}

      - name: Run Aqua Security Trivy for HIGH severity
        id: trivy
        uses: aquasecurity/trivy-action@master
        with:          
          scan-type: 'fs'
          format: 'table'
          severity: 'HIGH'
          output: 'trivy-scan.txt'

      - name: Echo contents of trivy-scan.txt
        run: |
            if test -f trivy-scan.txt; then
                cat trivy-scan.txt
            else
                echo "trivy-scan.txt does not exist."
                exit 1
            fi

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: success
          SLACK_MESSAGE: |
            Image build and signed
            Name: Jefri
            Matriculation: abc123
            Email: e1332826@u.nus.edu
            Git: https://github.com/Joot24/GDipSA58_CICD_CA
          #SLACK_FILE_UPLOAD: trivy-scan.txt
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}






        #- name: Upload report
        #if: ${{ steps.trivy.outputs.exit_code == 1 }} 
       # uses: actions/upload-artifact@v2
        #with:
         # name: trivy-scan
          #path: trivy-scan.txt
          #destination: input





            
            