name: Build and Push
on:
  push:
    #branches:
    #- release/v[0-9]+.[0-9]+ 

jobs:
  Scanning-Security-Vulnerabilities:
    if: "!startsWith(github.event.head_commit.message, '#NORUN')"
    runs-on: ubuntu-latest
    steps:             
      - name: Checkout source code
        uses: actions/checkout@v4.1.4
        with:
          ref: ${{ github.base_ref }}

      - name: Run Aqua Security Trivy for HIGH severity
        id: trivy
        uses: aquasecurity/trivy-action@master
        with:          
          scan-type: 'fs'
          format: 'table'
          severity: 'HIGH'
          output: 'trivy-scan.txt'

      - name: Echo contents of trivy-scan.txt
        run: |
            if test -f trivy-scan.txt; then
                cat trivy-scan.txt
            else
                echo "trivy-scan.txt does not exist."
                exit 1
            fi

      - name: Slack Notification on success
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: success
          SLACK_TITLE: '*Image build and signed*'
          SLACK_MESSAGE: |            
            *Name:* Too Chang Geng Jefri
            *Matriculation:* A0035383H
            *Email:* e1332826@u.nus.edu
            *Git:* ${{ github.repositoryUrl }}     
            *Image:* TBC
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Slack Notification on failure
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: 
          SLACK_COLOR: failure
          SLACK_TITLE: '*Scan failed - Jefri*'
          SLACK_MESSAGE: 'Failed trivy scan, see uploaded report'
          #SLACK_FILE_UPLOAD: trivy-scan.txt
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          #SLACK_TOKEN: ${{ secrets.RICH_TOKEN }}

      - uses: MeilCli/slack-upload-file@v4      
        with:
          slack_token: ${{ secrets.RICH_TOKEN }}
          channel_id: ${{ secrets.RICH_CHANNELID }}
          file_path: 'trivy-scan.txt'
          initial_comment: 'Scan report by Jefri'

      
            